name: Multi-Environment Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building the project..."

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: staging
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to staging environment..."

  deploy-to-preprod:
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    environment: 
      name: preprod
    steps:
      - name: Deploy to PreProd
        run: echo "Deploying to preprod environment..."

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: deploy-to-preprod
    environment: 
      name: prod
    steps:
      - name: Deploy to Prod
        run: echo "Deploying to production environment..."
