name: Your Workflow Name

on:
  push:
    branches:
      - main # Adjust branch name as needed

jobs:
  helm_nginx_deploy_preprod:
    runs-on: ubuntu-latest
    env:
      job_name: ${{ github.job }}
      environment: ''

    steps:
      - name: Set Environment Variable
        run: |
          job_name=${{ github.job }}
          if [[ $job_name == *"preprod"* ]]; then
            echo "ENVIRONMENT=pre" >> $GITHUB_ENV
          else [[ $job_name == *"prod"* ]]; then
            echo "ENVIRONMENT=pre" >> $GITHUB_ENV
          
          fi
          
          
