name: Approval Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Test
        run: echo "Running build and test steps..."

  wait-for-approval:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: 
      name: staging
    steps:
      - name: Wait for Approval
        run: echo "This job waits for manual approval in the 'staging' environment."

  deploy:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    steps:
      - name: Deploy
        run: echo "Deploying the application..."
