name: User Approval Workflow

on:
  workflow_dispatch:
    inputs:
      user_approval:
        description: 'Approve the user'
        required: true
        default: 'no'

jobs:
  user_approval_job:
    runs-on: ubuntu-latest
    if: github.event.inputs.user_approval == 'yes'
    steps:
      - name: Approval Step
        run: |
          # Get the provided user ID from the workflow dispatch input
          provided_user_id=$INPUT_USER_ID

          # Define the expected user ID (You might want to store this securely as a secret)
          expected_user_id='SureshUppelli'

          # Check if the provided user ID matches the expected user ID
          if [ "$provided_user_id" == "$expected_user_id" ]; then
            echo "User ID is verified."
            # Perform actions after successful user ID verification
            # For example, trigger subsequent steps or execute specific commands
          else
            echo "User ID does not match the expected value."
            # Handle the case where the user ID does not match
            # You can exit the workflow or perform specific actions based on your needs
            exit 1
          fi
