name: User Approval Workflow

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the workflow

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup build
        run: echo "Preparing the build..."

  wait-for-approval:
    runs-on: ubuntu-latest
    needs: prepare
    environment: 
      name: staging  # The environment name you set in the repository settings
    steps:
      - name: Wait for approval
        run: echo "Waiting for user approval..."

  execute-after-approval:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    steps:
      - name: Execute post-approval steps
        run: |
          echo "Approved! Executing further steps..."
          # Add more commands or actions here as needed
